epochs: 10
root_dir: ${oc.env:PWD}
data:
  name: cifar
  config:
    dir_train: ${root_dir}/datasets/local/train/
    dir_val: ${root_dir}/datasets/local/val/
    dir_test: ${root_dir}/datasets/global_test/
    batch_size: 32
model:
  name: cifar
  config:
    input_shape: 3
    mid_shape: 6
    n_classes: 10
    lr: 0.001

gpu: 0