config_client:
  cid: 3
  fabric:
    accelerator: cpu
    # accelerator: gpu
    # devices:
    #   - 0
  root_dir: ${oc.env:PWD}
  model:
    name: cifar
    config:
      input_shape: 3
      mid_shape: 6
      n_classes: 10
      lr: 0.001
  data:
    name: cifar
    config:
      dir_train: ${config_client.root_dir}/datasets/client2/train/
      dir_val: ${config_client.root_dir}/datasets/client2/val/
      dir_test: None
      batch_size: 32
  server_adress: localhost:22222
