config_client:
  cid: 1
  pre_train_val: true
  fabric:
    accelerator: cpu
    # accelerator: gpu
    # devices:
    #   - 0
  root_dir: ${oc.env:PWD}
  # root_dir: /home/mrbourbaki/pybiscus
  model:
    name: cifar
    config:
      input_shape: 3
      mid_shape: 6
      n_classes: 10
      lr: 0.001
  data:
    name: cifar
    config:
      # dir_train: ${root_dir}/datasets/client1/train/
      # dir_val: ${root_dir}/datasets/client1/val/
      dir_train: /home/mrbourbaki/pybiscus/datasets/client1/train/
      dir_val: /home/mrbourbaki/pybiscus/datasets/client1/val/
      dir_test: None
      batch_size: 32
  server_adress: localhost:22222
